// AUTO-GENERATED by scripts/build-catalog.mjs — do not edit by hand.
// Source: data/lists/*.json (scraped from Hibiki's Google Maps saved lists).
import type { Restaurant } from "./types";

export const generatedRestaurants: Restaurant[] = [
  {
    "id": "なるきよ-1",
    "name": "なるきよ",
    "cuisine": "和食",
    "priceTier": "casual",
    "priceDinner": "¥5,000〜",
    "scenes": [
      "カジュアル"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.685199999999995,
    "lng": 139.76043333333334,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E3%81%AA%E3%82%8B%E3%81%8D%E3%82%88%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "なるきよ 東京",
    "image": "https://images.unsplash.com/photo-1607301405390-d831c242f59b?w=800&q=80",
    "rating": 4.2,
    "reviewCount": 0,
    "tags": [
      "居酒屋"
    ],
    "description": "居酒屋。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "銀座あんどう-2",
    "name": "銀座あんどう",
    "cuisine": "和食",
    "priceTier": "casual",
    "priceDinner": "¥5,000〜",
    "scenes": [
      "カジュアル"
    ],
    "area": "銀座",
    "address": "東京都（銀座周辺）",
    "nearestStation": "",
    "lat": 35.66911666666667,
    "lng": 139.77215,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E9%8A%80%E5%BA%A7%E3%81%82%E3%82%93%E3%81%A9%E3%81%86%20%E9%8A%80%E5%BA%A7",
    "googlePlaceQuery": "銀座あんどう 銀座",
    "image": "https://images.unsplash.com/photo-1519690889869-e705e59f72e1?w=800&q=80",
    "rating": 4.1,
    "reviewCount": 0,
    "tags": [
      "居酒屋"
    ],
    "description": "居酒屋。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "楽食ふじた-3",
    "name": "楽食ふじた",
    "cuisine": "和食",
    "priceTier": "middle",
    "priceDinner": "¥10,000〜",
    "scenes": [
      "会食"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.686366666666665,
    "lng": 139.76993333333334,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E6%A5%BD%E9%A3%9F%E3%81%B5%E3%81%98%E3%81%9F%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "楽食ふじた 東京",
    "image": "https://images.unsplash.com/photo-1569058242567-93de6f36f8eb?w=800&q=80",
    "rating": 4.5,
    "reviewCount": 0,
    "tags": [
      "純和食店"
    ],
    "description": "純和食店。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "うなぎ-かぶと-4",
    "name": "うなぎ かぶと",
    "cuisine": "和食",
    "priceTier": "middle",
    "priceDinner": "¥10,000〜",
    "scenes": [
      "会食"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.68678333333333,
    "lng": 139.77151666666666,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E3%81%86%E3%81%AA%E3%81%8E%20%E3%81%8B%E3%81%B6%E3%81%A8%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "うなぎ かぶと 東京",
    "image": "https://images.unsplash.com/photo-1569058242567-93de6f36f8eb?w=800&q=80",
    "rating": 4.5,
    "reviewCount": 0,
    "tags": [
      "うなぎ料理店"
    ],
    "description": "うなぎ料理店。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "旨いもん割烹-輝咲-5",
    "name": "旨いもん割烹 輝咲",
    "cuisine": "和食",
    "priceTier": "middle",
    "priceDinner": "¥10,000〜",
    "scenes": [
      "会食"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.68895,
    "lng": 139.77268333333333,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E6%97%A8%E3%81%84%E3%82%82%E3%82%93%E5%89%B2%E7%83%B9%20%E8%BC%9D%E5%92%B2%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "旨いもん割烹 輝咲 東京",
    "image": "https://images.unsplash.com/photo-1607301405390-d831c242f59b?w=800&q=80",
    "rating": 4.5,
    "reviewCount": 0,
    "tags": [
      "和食店"
    ],
    "description": "和食店。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "西麻布-清水-6",
    "name": "西麻布 清水",
    "cuisine": "和食",
    "priceTier": "middle",
    "priceDinner": "¥10,000〜",
    "scenes": [
      "接待"
    ],
    "area": "六本木",
    "address": "東京都（六本木周辺）",
    "nearestStation": "",
    "lat": 35.660466666666665,
    "lng": 139.73183333333336,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E8%A5%BF%E9%BA%BB%E5%B8%83%20%E6%B8%85%E6%B0%B4%20%E5%85%AD%E6%9C%AC%E6%9C%A8",
    "googlePlaceQuery": "西麻布 清水 六本木",
    "image": "https://images.unsplash.com/photo-1553621042-f6e147245754?w=800&q=80",
    "rating": 4.8,
    "reviewCount": 0,
    "tags": [
      "和食店"
    ],
    "description": "和食店。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "和食-青-代々木上原店-7",
    "name": "和食 青 代々木上原店",
    "cuisine": "和食",
    "priceTier": "casual",
    "priceDinner": "¥5,000〜",
    "scenes": [
      "カジュアル"
    ],
    "area": "渋谷",
    "address": "東京都（渋谷周辺）",
    "nearestStation": "",
    "lat": 35.670883333333336,
    "lng": 139.67671666666666,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E5%92%8C%E9%A3%9F%20%E9%9D%92%20%E4%BB%A3%E3%80%85%E6%9C%A8%E4%B8%8A%E5%8E%9F%E5%BA%97%20%E6%B8%8B%E8%B0%B7",
    "googlePlaceQuery": "和食 青 代々木上原店 渋谷",
    "image": "https://images.unsplash.com/photo-1519690889869-e705e59f72e1?w=800&q=80",
    "rating": 3.7,
    "reviewCount": 0,
    "tags": [
      "居酒屋"
    ],
    "description": "居酒屋。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "味満ん-8",
    "name": "味満ん",
    "cuisine": "和食",
    "priceTier": "middle",
    "priceDinner": "¥10,000〜",
    "scenes": [
      "接待"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.6847,
    "lng": 139.76493333333335,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E5%91%B3%E6%BA%80%E3%82%93%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "味満ん 東京",
    "image": "https://images.unsplash.com/photo-1569058242567-93de6f36f8eb?w=800&q=80",
    "rating": 4.6,
    "reviewCount": 0,
    "tags": [
      "ふぐ料理店"
    ],
    "description": "ふぐ料理店。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "季節料理-小伝馬-9",
    "name": "季節料理 小伝馬",
    "cuisine": "和食",
    "priceTier": "middle",
    "priceDinner": "¥10,000〜",
    "scenes": [
      "会食"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.68353333333333,
    "lng": 139.76076666666665,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E5%AD%A3%E7%AF%80%E6%96%99%E7%90%86%20%E5%B0%8F%E4%BC%9D%E9%A6%AC%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "季節料理 小伝馬 東京",
    "image": "https://images.unsplash.com/photo-1607301405390-d831c242f59b?w=800&q=80",
    "rating": 4.1,
    "reviewCount": 0,
    "tags": [
      "シーフード・海鮮料理店"
    ],
    "description": "シーフード・海鮮料理店。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "あかぎ-10",
    "name": "あかぎ",
    "cuisine": "和食",
    "priceTier": "casual",
    "priceDinner": "¥5,000〜",
    "scenes": [
      "カジュアル"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.687949999999994,
    "lng": 139.76301666666666,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E3%81%82%E3%81%8B%E3%81%8E%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "あかぎ 東京",
    "image": "https://images.unsplash.com/photo-1580822184713-fc5400e7fe10?w=800&q=80",
    "rating": 4.5,
    "reviewCount": 0,
    "tags": [
      "居酒屋"
    ],
    "description": "居酒屋。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "荒木町たつや-11",
    "name": "荒木町たつや",
    "cuisine": "和食",
    "priceTier": "middle",
    "priceDinner": "¥10,000〜",
    "scenes": [
      "接待"
    ],
    "area": "新宿",
    "address": "東京都（新宿周辺）",
    "nearestStation": "",
    "lat": 35.69181666666667,
    "lng": 139.71925,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E8%8D%92%E6%9C%A8%E7%94%BA%E3%81%9F%E3%81%A4%E3%82%84%20%E6%96%B0%E5%AE%BF",
    "googlePlaceQuery": "荒木町たつや 新宿",
    "image": "https://images.unsplash.com/photo-1569058242567-93de6f36f8eb?w=800&q=80",
    "rating": 4.7,
    "reviewCount": 0,
    "tags": [
      "和食店"
    ],
    "description": "和食店。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "大衆酒場-豊田屋-12",
    "name": "大衆酒場 豊田屋",
    "cuisine": "和食",
    "priceTier": "casual",
    "priceDinner": "¥5,000〜",
    "scenes": [
      "カジュアル"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.68203333333333,
    "lng": 139.76693333333333,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E5%A4%A7%E8%A1%86%E9%85%92%E5%A0%B4%20%E8%B1%8A%E7%94%B0%E5%B1%8B%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "大衆酒場 豊田屋 東京",
    "image": "https://images.unsplash.com/photo-1553621042-f6e147245754?w=800&q=80",
    "rating": 4,
    "reviewCount": 0,
    "tags": [
      "居酒屋"
    ],
    "description": "居酒屋。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "高太郎-13",
    "name": "高太郎",
    "cuisine": "和食",
    "priceTier": "casual",
    "priceDinner": "¥5,000〜",
    "scenes": [
      "カジュアル"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.673199999999994,
    "lng": 139.76376666666667,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E9%AB%98%E5%A4%AA%E9%83%8E%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "高太郎 東京",
    "image": "https://images.unsplash.com/photo-1519690889869-e705e59f72e1?w=800&q=80",
    "rating": 4.3,
    "reviewCount": 0,
    "tags": [
      "居酒屋"
    ],
    "description": "居酒屋。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "鮨かみなり-14",
    "name": "鮨かみなり",
    "cuisine": "鮨",
    "priceTier": "middle",
    "priceDinner": "¥10,000〜",
    "scenes": [
      "接待"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.6752,
    "lng": 139.75976666666668,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E9%AE%A8%E3%81%8B%E3%81%BF%E3%81%AA%E3%82%8A%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "鮨かみなり 東京",
    "image": "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800&q=80",
    "rating": 4.7,
    "reviewCount": 0,
    "tags": [
      "和食店"
    ],
    "description": "和食店。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "日本料理-晴山-15",
    "name": "日本料理 晴山",
    "cuisine": "和食",
    "priceTier": "executive",
    "priceDinner": "¥20,000〜",
    "scenes": [
      "会食",
      "とっておき",
      "記念日",
      "接待"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.67628333333333,
    "lng": 139.76935,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E6%97%A5%E6%9C%AC%E6%96%99%E7%90%86%20%E6%99%B4%E5%B1%B1%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "日本料理 晴山 東京",
    "image": "https://images.unsplash.com/photo-1580822184713-fc5400e7fe10?w=800&q=80",
    "rating": 4.7,
    "reviewCount": 0,
    "tags": [
      "会席・懐石料理店"
    ],
    "description": "会席・懐石料理店。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": true,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "紀尾井町-とんかつ洋食-ひとみ-16",
    "name": "紀尾井町 とんかつ・洋食 ひとみ",
    "cuisine": "和食",
    "priceTier": "middle",
    "priceDinner": "¥10,000〜",
    "scenes": [
      "会食"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.68078333333333,
    "lng": 139.76218333333333,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E7%B4%80%E5%B0%BE%E4%BA%95%E7%94%BA%20%E3%81%A8%E3%82%93%E3%81%8B%E3%81%A4%E3%83%BB%E6%B4%8B%E9%A3%9F%20%E3%81%B2%E3%81%A8%E3%81%BF%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "紀尾井町 とんかつ・洋食 ひとみ 東京",
    "image": "https://images.unsplash.com/photo-1553621042-f6e147245754?w=800&q=80",
    "rating": 3.7,
    "reviewCount": 0,
    "tags": [
      "とんかつ店"
    ],
    "description": "とんかつ店。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "和食割烹-鈴なり-17",
    "name": "和食割烹 鈴なり",
    "cuisine": "和食",
    "priceTier": "executive",
    "priceDinner": "¥20,000〜",
    "scenes": [
      "会食",
      "とっておき",
      "接待"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.680699999999995,
    "lng": 139.76693333333333,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E5%92%8C%E9%A3%9F%E5%89%B2%E7%83%B9%20%E9%88%B4%E3%81%AA%E3%82%8A%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "和食割烹 鈴なり 東京",
    "image": "https://images.unsplash.com/photo-1519690889869-e705e59f72e1?w=800&q=80",
    "rating": 4.6,
    "reviewCount": 0,
    "tags": [
      "会席・懐石料理店"
    ],
    "description": "会席・懐石料理店。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": true,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "寿々屋-18",
    "name": "寿々屋",
    "cuisine": "和食",
    "priceTier": "middle",
    "priceDinner": "¥10,000〜",
    "scenes": [
      "会食"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.67995,
    "lng": 139.77368333333334,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E5%AF%BF%E3%80%85%E5%B1%8B%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "寿々屋 東京",
    "image": "https://images.unsplash.com/photo-1553621042-f6e147245754?w=800&q=80",
    "rating": 4.3,
    "reviewCount": 0,
    "tags": [
      "閉業"
    ],
    "description": "閉業。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "あらいかわ-19",
    "name": "あらいかわ",
    "cuisine": "和食",
    "priceTier": "executive",
    "priceDinner": "¥20,000〜",
    "scenes": [
      "会食",
      "とっておき",
      "接待"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.67361666666666,
    "lng": 139.76601666666667,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E3%81%82%E3%82%89%E3%81%84%E3%81%8B%E3%82%8F%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "あらいかわ 東京",
    "image": "https://images.unsplash.com/photo-1519690889869-e705e59f72e1?w=800&q=80",
    "rating": 4.6,
    "reviewCount": 0,
    "tags": [
      "会席・懐石料理店"
    ],
    "description": "会席・懐石料理店。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": true,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "わたなべ-20",
    "name": "わたなべ",
    "cuisine": "和食",
    "priceTier": "middle",
    "priceDinner": "¥10,000〜",
    "scenes": [
      "接待"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.676116666666665,
    "lng": 139.77218333333334,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E3%82%8F%E3%81%9F%E3%81%AA%E3%81%B9%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "わたなべ 東京",
    "image": "https://images.unsplash.com/photo-1519690889869-e705e59f72e1?w=800&q=80",
    "rating": 4.8,
    "reviewCount": 0,
    "tags": [
      "和食店"
    ],
    "description": "和食店。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "ふぐ俱楽部-miyawaki-別邸-21",
    "name": "ふぐ俱楽部 miyawaki 別邸",
    "cuisine": "和食",
    "priceTier": "middle",
    "priceDinner": "¥10,000〜",
    "scenes": [
      "接待"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.6782,
    "lng": 139.76743333333334,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E3%81%B5%E3%81%90%E4%BF%B1%E6%A5%BD%E9%83%A8%20miyawaki%20%E5%88%A5%E9%82%B8%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "ふぐ俱楽部 miyawaki 別邸 東京",
    "image": "https://images.unsplash.com/photo-1519690889869-e705e59f72e1?w=800&q=80",
    "rating": 4.6,
    "reviewCount": 0,
    "tags": [
      "ふぐ料理店"
    ],
    "description": "ふぐ料理店。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "和田-22",
    "name": "和田",
    "cuisine": "和食",
    "priceTier": "middle",
    "priceDinner": "¥10,000〜",
    "scenes": [
      "会食"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.673199999999994,
    "lng": 139.77443333333332,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E5%92%8C%E7%94%B0%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "和田 東京",
    "image": "https://images.unsplash.com/photo-1519690889869-e705e59f72e1?w=800&q=80",
    "rating": 4.3,
    "reviewCount": 0,
    "tags": [
      "会席・懐石料理店"
    ],
    "description": "会席・懐石料理店。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": true,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "懐石-辻留-23",
    "name": "懐石 辻留",
    "cuisine": "和食",
    "priceTier": "middle",
    "priceDinner": "¥10,000〜",
    "scenes": [
      "会食"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.68578333333333,
    "lng": 139.76851666666667,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E6%87%90%E7%9F%B3%20%E8%BE%BB%E7%95%99%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "懐石 辻留 東京",
    "image": "https://images.unsplash.com/photo-1553621042-f6e147245754?w=800&q=80",
    "rating": 4.3,
    "reviewCount": 0,
    "tags": [
      "会席・懐石料理店"
    ],
    "description": "会席・懐石料理店。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": true,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "こはぜ-24",
    "name": "こはぜ",
    "cuisine": "和食",
    "priceTier": "middle",
    "priceDinner": "¥10,000〜",
    "scenes": [
      "会食"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.67686666666666,
    "lng": 139.76743333333334,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E3%81%93%E3%81%AF%E3%81%9C%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "こはぜ 東京",
    "image": "https://images.unsplash.com/photo-1607301405390-d831c242f59b?w=800&q=80",
    "rating": 4.5,
    "reviewCount": 0,
    "tags": [
      "和食店"
    ],
    "description": "和食店。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "eat-鮨と和食-25",
    "name": "eat 鮨と和食",
    "cuisine": "鮨",
    "priceTier": "middle",
    "priceDinner": "¥10,000〜",
    "scenes": [
      "会食"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.68045,
    "lng": 139.76585,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=eat%20%E9%AE%A8%E3%81%A8%E5%92%8C%E9%A3%9F%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "eat 鮨と和食 東京",
    "image": "https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56?w=800&q=80",
    "rating": 4.1,
    "reviewCount": 0,
    "tags": [
      "寿司店"
    ],
    "description": "寿司店。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "月-26",
    "name": "月",
    "cuisine": "和食",
    "priceTier": "middle",
    "priceDinner": "¥10,000〜",
    "scenes": [
      "会食"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.68753333333333,
    "lng": 139.77076666666667,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E6%9C%88%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "月 東京",
    "image": "https://images.unsplash.com/photo-1580822184713-fc5400e7fe10?w=800&q=80",
    "rating": 4.4,
    "reviewCount": 0,
    "tags": [
      "和食店"
    ],
    "description": "和食店。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "割烹料理-霞町三一ノ一-西麻布-27",
    "name": "割烹料理 霞町三◯一ノ一 西麻布",
    "cuisine": "和食",
    "priceTier": "middle",
    "priceDinner": "¥10,000〜",
    "scenes": [
      "会食"
    ],
    "area": "六本木",
    "address": "東京都（六本木周辺）",
    "nearestStation": "",
    "lat": 35.65071666666667,
    "lng": 139.7229166666667,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E5%89%B2%E7%83%B9%E6%96%99%E7%90%86%20%E9%9C%9E%E7%94%BA%E4%B8%89%E2%97%AF%E4%B8%80%E3%83%8E%E4%B8%80%20%E8%A5%BF%E9%BA%BB%E5%B8%83%20%E5%85%AD%E6%9C%AC%E6%9C%A8",
    "googlePlaceQuery": "割烹料理 霞町三◯一ノ一 西麻布 六本木",
    "image": "https://images.unsplash.com/photo-1607301405390-d831c242f59b?w=800&q=80",
    "rating": 4.5,
    "reviewCount": 0,
    "tags": [
      "和食店"
    ],
    "description": "和食店。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "居酒屋-赤鬼-28",
    "name": "居酒屋 赤鬼",
    "cuisine": "和食",
    "priceTier": "casual",
    "priceDinner": "¥5,000〜",
    "scenes": [
      "カジュアル"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.674366666666664,
    "lng": 139.7726,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E5%B1%85%E9%85%92%E5%B1%8B%20%E8%B5%A4%E9%AC%BC%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "居酒屋 赤鬼 東京",
    "image": "https://images.unsplash.com/photo-1607301405390-d831c242f59b?w=800&q=80",
    "rating": 4.1,
    "reviewCount": 0,
    "tags": [
      "居酒屋"
    ],
    "description": "居酒屋。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "日本料理-青山浅田-29",
    "name": "日本料理 青山浅田",
    "cuisine": "和食",
    "priceTier": "middle",
    "priceDinner": "¥10,000〜",
    "scenes": [
      "会食"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.67176666666666,
    "lng": 139.70653333333334,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E6%97%A5%E6%9C%AC%E6%96%99%E7%90%86%20%E9%9D%92%E5%B1%B1%E6%B5%85%E7%94%B0%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "日本料理 青山浅田 東京",
    "image": "https://images.unsplash.com/photo-1519690889869-e705e59f72e1?w=800&q=80",
    "rating": 4.5,
    "reviewCount": 0,
    "tags": [
      "高級料理レストラン"
    ],
    "description": "高級料理レストラン。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "日本料理-赤坂浅田-30",
    "name": "日本料理 赤坂浅田",
    "cuisine": "和食",
    "priceTier": "middle",
    "priceDinner": "¥10,000〜",
    "scenes": [
      "会食"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.666583333333335,
    "lng": 139.74385,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E6%97%A5%E6%9C%AC%E6%96%99%E7%90%86%20%E8%B5%A4%E5%9D%82%E6%B5%85%E7%94%B0%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "日本料理 赤坂浅田 東京",
    "image": "https://images.unsplash.com/photo-1553621042-f6e147245754?w=800&q=80",
    "rating": 4.4,
    "reviewCount": 0,
    "tags": [
      "高級料理レストラン"
    ],
    "description": "高級料理レストラン。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "壱縁-31",
    "name": "壱縁",
    "cuisine": "和食",
    "priceTier": "casual",
    "priceDinner": "¥5,000〜",
    "scenes": [
      "カジュアル"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.672866666666664,
    "lng": 139.76143333333334,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E5%A3%B1%E7%B8%81%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "壱縁 東京",
    "image": "https://images.unsplash.com/photo-1553621042-f6e147245754?w=800&q=80",
    "rating": 4.5,
    "reviewCount": 0,
    "tags": [
      "居酒屋"
    ],
    "description": "居酒屋。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "稲垣-32",
    "name": "稲垣",
    "cuisine": "和食",
    "priceTier": "casual",
    "priceDinner": "¥5,000〜",
    "scenes": [
      "カジュアル"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.68428333333333,
    "lng": 139.76068333333333,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E7%A8%B2%E5%9E%A3%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "稲垣 東京",
    "image": "https://images.unsplash.com/photo-1569058242567-93de6f36f8eb?w=800&q=80",
    "rating": 4.2,
    "reviewCount": 0,
    "tags": [
      "居酒屋"
    ],
    "description": "居酒屋。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "たきや-33",
    "name": "たきや",
    "cuisine": "和食",
    "priceTier": "middle",
    "priceDinner": "¥10,000〜",
    "scenes": [
      "接待"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.686699999999995,
    "lng": 139.7656,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E3%81%9F%E3%81%8D%E3%82%84%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "たきや 東京",
    "image": "https://images.unsplash.com/photo-1580822184713-fc5400e7fe10?w=800&q=80",
    "rating": 4.6,
    "reviewCount": 0,
    "tags": [
      "天ぷら店"
    ],
    "description": "天ぷら店。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "新ばし-星野-34",
    "name": "新ばし 星野",
    "cuisine": "和食",
    "priceTier": "executive",
    "priceDinner": "¥20,000〜",
    "scenes": [
      "会食",
      "とっておき",
      "記念日",
      "接待"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.68553333333333,
    "lng": 139.7721,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E6%96%B0%E3%81%B0%E3%81%97%20%E6%98%9F%E9%87%8E%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "新ばし 星野 東京",
    "image": "https://images.unsplash.com/photo-1569058242567-93de6f36f8eb?w=800&q=80",
    "rating": 4.9,
    "reviewCount": 0,
    "tags": [
      "会席・懐石料理店"
    ],
    "description": "会席・懐石料理店。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": true,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "日本料理-久丹-35",
    "name": "日本料理 久丹",
    "cuisine": "和食",
    "priceTier": "middle",
    "priceDinner": "¥10,000〜",
    "scenes": [
      "会食"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.6802,
    "lng": 139.76276666666666,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E6%97%A5%E6%9C%AC%E6%96%99%E7%90%86%20%E4%B9%85%E4%B8%B9%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "日本料理 久丹 東京",
    "image": "https://images.unsplash.com/photo-1607301405390-d831c242f59b?w=800&q=80",
    "rating": 4.2,
    "reviewCount": 0,
    "tags": [
      "会席・懐石料理店"
    ],
    "description": "会席・懐石料理店。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": true,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "膳司-水光庵-36",
    "name": "膳司 水光庵",
    "cuisine": "和食",
    "priceTier": "middle",
    "priceDinner": "¥10,000〜",
    "scenes": [
      "接待"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.683949999999996,
    "lng": 139.76168333333334,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E8%86%B3%E5%8F%B8%20%E6%B0%B4%E5%85%89%E5%BA%B5%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "膳司 水光庵 東京",
    "image": "https://images.unsplash.com/photo-1607301405390-d831c242f59b?w=800&q=80",
    "rating": 4.9,
    "reviewCount": 0,
    "tags": [
      "和食店"
    ],
    "description": "和食店。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "麻布-かどわき-37",
    "name": "麻布 かどわき",
    "cuisine": "和食",
    "priceTier": "middle",
    "priceDinner": "¥10,000〜",
    "scenes": [
      "会食"
    ],
    "area": "六本木",
    "address": "東京都（六本木周辺）",
    "nearestStation": "",
    "lat": 35.664500000000004,
    "lng": 139.7312,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E9%BA%BB%E5%B8%83%20%E3%81%8B%E3%81%A9%E3%82%8F%E3%81%8D%20%E5%85%AD%E6%9C%AC%E6%9C%A8",
    "googlePlaceQuery": "麻布 かどわき 六本木",
    "image": "https://images.unsplash.com/photo-1580822184713-fc5400e7fe10?w=800&q=80",
    "rating": 4.2,
    "reviewCount": 0,
    "tags": [
      "会席・懐石料理店"
    ],
    "description": "会席・懐石料理店。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": true,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "松川-38",
    "name": "松川",
    "cuisine": "和食",
    "priceTier": "executive",
    "priceDinner": "¥20,000〜",
    "scenes": [
      "会食",
      "とっておき",
      "記念日",
      "接待"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.682116666666666,
    "lng": 139.76618333333334,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E6%9D%BE%E5%B7%9D%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "松川 東京",
    "image": "https://images.unsplash.com/photo-1580822184713-fc5400e7fe10?w=800&q=80",
    "rating": 4.7,
    "reviewCount": 0,
    "tags": [
      "会席・懐石料理店"
    ],
    "description": "会席・懐石料理店。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": true,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "みつ芳-39",
    "name": "みつ芳",
    "cuisine": "和食",
    "priceTier": "middle",
    "priceDinner": "¥10,000〜",
    "scenes": [
      "接待"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.68403333333333,
    "lng": 139.7676,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E3%81%BF%E3%81%A4%E8%8A%B3%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "みつ芳 東京",
    "image": "https://images.unsplash.com/photo-1519690889869-e705e59f72e1?w=800&q=80",
    "rating": 4.8,
    "reviewCount": 0,
    "tags": [
      "レストラン"
    ],
    "description": "レストラン。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "喰切り江ぐち-40",
    "name": "喰切り江ぐち",
    "cuisine": "和食",
    "priceTier": "middle",
    "priceDinner": "¥10,000〜",
    "scenes": [
      "会食"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.68194999999999,
    "lng": 139.76101666666668,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E5%96%B0%E5%88%87%E3%82%8A%E6%B1%9F%E3%81%90%E3%81%A1%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "喰切り江ぐち 東京",
    "image": "https://images.unsplash.com/photo-1519690889869-e705e59f72e1?w=800&q=80",
    "rating": 4.2,
    "reviewCount": 0,
    "tags": [
      "和食店"
    ],
    "description": "和食店。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "恵比寿くろいわ-41",
    "name": "恵比寿くろいわ",
    "cuisine": "和食",
    "priceTier": "executive",
    "priceDinner": "¥20,000〜",
    "scenes": [
      "会食",
      "とっておき",
      "接待"
    ],
    "area": "渋谷",
    "address": "東京都（渋谷周辺）",
    "nearestStation": "",
    "lat": 35.639783333333334,
    "lng": 139.71825,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E6%81%B5%E6%AF%94%E5%AF%BF%E3%81%8F%E3%82%8D%E3%81%84%E3%82%8F%20%E6%B8%8B%E8%B0%B7",
    "googlePlaceQuery": "恵比寿くろいわ 渋谷",
    "image": "https://images.unsplash.com/photo-1569058242567-93de6f36f8eb?w=800&q=80",
    "rating": 4.6,
    "reviewCount": 0,
    "tags": [
      "会席・懐石料理店"
    ],
    "description": "会席・懐石料理店。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": true,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "山﨑-42",
    "name": "山﨑",
    "cuisine": "和食",
    "priceTier": "executive",
    "priceDinner": "¥20,000〜",
    "scenes": [
      "会食",
      "とっておき",
      "接待"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.672866666666664,
    "lng": 139.7621,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E5%B1%B1%EF%A8%91%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "山﨑 東京",
    "image": "https://images.unsplash.com/photo-1553621042-f6e147245754?w=800&q=80",
    "rating": 4.6,
    "reviewCount": 0,
    "tags": [
      "会席・懐石料理店"
    ],
    "description": "会席・懐石料理店。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": true,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "きんはる-代々木上原店-43",
    "name": "きんはる 代々木上原店",
    "cuisine": "和食",
    "priceTier": "middle",
    "priceDinner": "¥10,000〜",
    "scenes": [
      "会食"
    ],
    "area": "渋谷",
    "address": "東京都（渋谷周辺）",
    "nearestStation": "",
    "lat": 35.6738,
    "lng": 139.68646666666666,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E3%81%8D%E3%82%93%E3%81%AF%E3%82%8B%20%E4%BB%A3%E3%80%85%E6%9C%A8%E4%B8%8A%E5%8E%9F%E5%BA%97%20%E6%B8%8B%E8%B0%B7",
    "googlePlaceQuery": "きんはる 代々木上原店 渋谷",
    "image": "https://images.unsplash.com/photo-1519690889869-e705e59f72e1?w=800&q=80",
    "rating": 4.3,
    "reviewCount": 0,
    "tags": [
      "臨時休業"
    ],
    "description": "臨時休業。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "くすのき-44",
    "name": "くすのき",
    "cuisine": "和食",
    "priceTier": "middle",
    "priceDinner": "¥10,000〜",
    "scenes": [
      "会食"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.67895,
    "lng": 139.76668333333333,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E3%81%8F%E3%81%99%E3%81%AE%E3%81%8D%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "くすのき 東京",
    "image": "https://images.unsplash.com/photo-1607301405390-d831c242f59b?w=800&q=80",
    "rating": 4.5,
    "reviewCount": 0,
    "tags": [
      "天ぷら店"
    ],
    "description": "天ぷら店。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "美の-45",
    "name": "美の",
    "cuisine": "和食",
    "priceTier": "middle",
    "priceDinner": "¥10,000〜",
    "scenes": [
      "会食"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.67553333333333,
    "lng": 139.76943333333332,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E7%BE%8E%E3%81%AE%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "美の 東京",
    "image": "https://images.unsplash.com/photo-1569058242567-93de6f36f8eb?w=800&q=80",
    "rating": 4.4,
    "reviewCount": 0,
    "tags": [
      "和食店"
    ],
    "description": "和食店。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "炭火割烹-白坂-46",
    "name": "炭火割烹 白坂",
    "cuisine": "和食",
    "priceTier": "executive",
    "priceDinner": "¥20,000〜",
    "scenes": [
      "会食",
      "とっておき",
      "接待"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.68686666666667,
    "lng": 139.7621,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E7%82%AD%E7%81%AB%E5%89%B2%E7%83%B9%20%E7%99%BD%E5%9D%82%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "炭火割烹 白坂 東京",
    "image": "https://images.unsplash.com/photo-1607301405390-d831c242f59b?w=800&q=80",
    "rating": 4.6,
    "reviewCount": 0,
    "tags": [
      "会席・懐石料理店"
    ],
    "description": "会席・懐石料理店。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": true,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "御料理-辻-おりょうり-つじ-47",
    "name": "御料理 辻 (おりょうり つじ)",
    "cuisine": "和食",
    "priceTier": "middle",
    "priceDinner": "¥10,000〜",
    "scenes": [
      "会食"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.679449999999996,
    "lng": 139.76351666666667,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E5%BE%A1%E6%96%99%E7%90%86%20%E8%BE%BB%20(%E3%81%8A%E3%82%8A%E3%82%87%E3%81%86%E3%82%8A%20%E3%81%A4%E3%81%98)%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "御料理 辻 (おりょうり つじ) 東京",
    "image": "https://images.unsplash.com/photo-1519690889869-e705e59f72e1?w=800&q=80",
    "rating": 4.4,
    "reviewCount": 0,
    "tags": [
      "会席・懐石料理店"
    ],
    "description": "会席・懐石料理店。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": true,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "傳-48",
    "name": "傳",
    "cuisine": "和食",
    "priceTier": "middle",
    "priceDinner": "¥10,000〜",
    "scenes": [
      "会食"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.67778333333333,
    "lng": 139.76918333333333,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E5%82%B3%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "傳 東京",
    "image": "https://images.unsplash.com/photo-1519690889869-e705e59f72e1?w=800&q=80",
    "rating": 4.4,
    "reviewCount": 0,
    "tags": [
      "和食店"
    ],
    "description": "和食店。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "八重洲-鰻-はし本-49",
    "name": "八重洲 鰻 はし本",
    "cuisine": "和食",
    "priceTier": "middle",
    "priceDinner": "¥10,000〜",
    "scenes": [
      "会食"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.68451666666667,
    "lng": 139.76458333333332,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E5%85%AB%E9%87%8D%E6%B4%B2%20%E9%B0%BB%20%E3%81%AF%E3%81%97%E6%9C%AC%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "八重洲 鰻 はし本 東京",
    "image": "https://images.unsplash.com/photo-1519690889869-e705e59f72e1?w=800&q=80",
    "rating": 4.4,
    "reviewCount": 0,
    "tags": [
      "うなぎ料理店"
    ],
    "description": "うなぎ料理店。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "明神下-神田川-本店-50",
    "name": "明神下 神田川 本店",
    "cuisine": "和食",
    "priceTier": "middle",
    "priceDinner": "¥10,000〜",
    "scenes": [
      "会食"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.69855,
    "lng": 139.7708166666667,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E6%98%8E%E7%A5%9E%E4%B8%8B%20%E7%A5%9E%E7%94%B0%E5%B7%9D%20%E6%9C%AC%E5%BA%97%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "明神下 神田川 本店 東京",
    "image": "https://images.unsplash.com/photo-1580822184713-fc5400e7fe10?w=800&q=80",
    "rating": 4.4,
    "reviewCount": 0,
    "tags": [
      "うなぎ料理店"
    ],
    "description": "うなぎ料理店。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "日本料理-太月-51",
    "name": "日本料理 太月",
    "cuisine": "和食",
    "priceTier": "middle",
    "priceDinner": "¥10,000〜",
    "scenes": [
      "会食"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.67503333333333,
    "lng": 139.77326666666667,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E6%97%A5%E6%9C%AC%E6%96%99%E7%90%86%20%E5%A4%AA%E6%9C%88%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "日本料理 太月 東京",
    "image": "https://images.unsplash.com/photo-1580822184713-fc5400e7fe10?w=800&q=80",
    "rating": 4.5,
    "reviewCount": 0,
    "tags": [
      "会席・懐石料理店"
    ],
    "description": "会席・懐石料理店。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": true,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "しのはら-52",
    "name": "しのはら",
    "cuisine": "和食",
    "priceTier": "executive",
    "priceDinner": "¥20,000〜",
    "scenes": [
      "会食",
      "とっておき",
      "接待"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.683616666666666,
    "lng": 139.76735,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E3%81%97%E3%81%AE%E3%81%AF%E3%82%89%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "しのはら 東京",
    "image": "https://images.unsplash.com/photo-1519690889869-e705e59f72e1?w=800&q=80",
    "rating": 4.6,
    "reviewCount": 0,
    "tags": [
      "会席・懐石料理店"
    ],
    "description": "会席・懐石料理店。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": true,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "天ぷら元吉-53",
    "name": "天ぷら元吉",
    "cuisine": "和食",
    "priceTier": "middle",
    "priceDinner": "¥10,000〜",
    "scenes": [
      "接待"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.68295,
    "lng": 139.77535,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E5%A4%A9%E3%81%B7%E3%82%89%E5%85%83%E5%90%89%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "天ぷら元吉 東京",
    "image": "https://images.unsplash.com/photo-1580822184713-fc5400e7fe10?w=800&q=80",
    "rating": 4.8,
    "reviewCount": 0,
    "tags": [
      "天ぷら店"
    ],
    "description": "天ぷら店。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "あんちゅう-代々木上原-54",
    "name": "あんちゅう 代々木上原",
    "cuisine": "和食",
    "priceTier": "middle",
    "priceDinner": "¥10,000〜",
    "scenes": [
      "会食"
    ],
    "area": "渋谷",
    "address": "東京都（渋谷周辺）",
    "nearestStation": "",
    "lat": 35.67463333333333,
    "lng": 139.6883,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E3%81%82%E3%82%93%E3%81%A1%E3%82%85%E3%81%86%20%E4%BB%A3%E3%80%85%E6%9C%A8%E4%B8%8A%E5%8E%9F%20%E6%B8%8B%E8%B0%B7",
    "googlePlaceQuery": "あんちゅう 代々木上原 渋谷",
    "image": "https://images.unsplash.com/photo-1519690889869-e705e59f72e1?w=800&q=80",
    "rating": 4.5,
    "reviewCount": 0,
    "tags": [
      "和食店"
    ],
    "description": "和食店。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "銘酒処-串駒-本店-55",
    "name": "銘酒処 串駒 本店",
    "cuisine": "和食",
    "priceTier": "casual",
    "priceDinner": "¥5,000〜",
    "scenes": [
      "カジュアル",
      "接待"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.68478333333333,
    "lng": 139.76818333333333,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E9%8A%98%E9%85%92%E5%87%A6%20%E4%B8%B2%E9%A7%92%20%E6%9C%AC%E5%BA%97%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "銘酒処 串駒 本店 東京",
    "image": "https://images.unsplash.com/photo-1607301405390-d831c242f59b?w=800&q=80",
    "rating": 4.6,
    "reviewCount": 0,
    "tags": [
      "居酒屋"
    ],
    "description": "居酒屋。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "うなぎ魚政-56",
    "name": "うなぎ魚政",
    "cuisine": "和食",
    "priceTier": "middle",
    "priceDinner": "¥10,000〜",
    "scenes": [
      "会食"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.67878333333333,
    "lng": 139.77351666666667,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E3%81%86%E3%81%AA%E3%81%8E%E9%AD%9A%E6%94%BF%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "うなぎ魚政 東京",
    "image": "https://images.unsplash.com/photo-1580822184713-fc5400e7fe10?w=800&q=80",
    "rating": 4.2,
    "reviewCount": 0,
    "tags": [
      "うなぎ料理店"
    ],
    "description": "うなぎ料理店。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "マルタ-57",
    "name": "マルタ",
    "cuisine": "和食",
    "priceTier": "middle",
    "priceDinner": "¥10,000〜",
    "scenes": [
      "会食"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.68103333333333,
    "lng": 139.7626,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E3%83%9E%E3%83%AB%E3%82%BF%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "マルタ 東京",
    "image": "https://images.unsplash.com/photo-1607301405390-d831c242f59b?w=800&q=80",
    "rating": 4.5,
    "reviewCount": 0,
    "tags": [
      "レストラン"
    ],
    "description": "レストラン。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "ぼたん-58",
    "name": "ぼたん",
    "cuisine": "和食",
    "priceTier": "middle",
    "priceDinner": "¥10,000〜",
    "scenes": [
      "会食"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.678866666666664,
    "lng": 139.7601,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E3%81%BC%E3%81%9F%E3%82%93%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "ぼたん 東京",
    "image": "https://images.unsplash.com/photo-1569058242567-93de6f36f8eb?w=800&q=80",
    "rating": 4.4,
    "reviewCount": 0,
    "tags": [
      "鶏料理店"
    ],
    "description": "鶏料理店。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  },
  {
    "id": "酒場たかや-日本酒と蕎麦と天麩羅-59",
    "name": "酒場たかや 日本酒と蕎麦と天麩羅",
    "cuisine": "和食",
    "priceTier": "middle",
    "priceDinner": "¥10,000〜",
    "scenes": [
      "会食"
    ],
    "area": "東京",
    "address": "東京都（東京周辺）",
    "nearestStation": "",
    "lat": 35.68253333333333,
    "lng": 139.7611,
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=%E9%85%92%E5%A0%B4%E3%81%9F%E3%81%8B%E3%82%84%20%E6%97%A5%E6%9C%AC%E9%85%92%E3%81%A8%E8%95%8E%E9%BA%A6%E3%81%A8%E5%A4%A9%E9%BA%A9%E7%BE%85%20%E6%9D%B1%E4%BA%AC",
    "googlePlaceQuery": "酒場たかや 日本酒と蕎麦と天麩羅 東京",
    "image": "https://images.unsplash.com/photo-1580822184713-fc5400e7fe10?w=800&q=80",
    "rating": 4.4,
    "reviewCount": 0,
    "tags": [
      "蕎麦店"
    ],
    "description": "蕎麦店。Googleマップの「東京レストラン_和食」より。",
    "privateRoom": false,
    "listSource": "東京レストラン_和食"
  }
];
