import type { Restaurant } from "./types";

function mapsUrl(query: string, lat: number, lng: number) {
  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}&query_place_id=&center=${lat},${lng}`;
}

/** Seed data inspired by Hibiki Nozawa's Google Maps saved lists */
export const restaurants: Restaurant[] = [
  {
    id: "tsukiji-sushi-sei",
    name: "すし誠",
    cuisine: "鮨",
    priceTier: "middle",
    priceLunch: "¥8,000〜",
    priceDinner: "¥15,000〜",
    scenes: ["会食", "個室", "接待"],
    area: "築地",
    address: "東京都中央区築地",
    nearestStation: "築地市場駅 徒歩5分",
    lat: 35.6654,
    lng: 139.7707,
    googleMapsUrl: mapsUrl("すし誠 築地", 35.6654, 139.7707),
    googlePlaceQuery: "すし誠 築地",
    image:
      "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800&q=80",
    rating: 4.6,
    reviewCount: 128,
    tags: ["カウンター", "旬魚", "会食向き"],
    description:
      "築地の名店。ミドルレンジの会食で安心して使える鮨。個室もあり接待にも。",
    privateRoom: true,
    capacity: 8,
    listSource: "東京レストラン_鮨 / 築地周辺レストラン",
  },
  {
    id: "ginza-kyubey",
    name: "久兵衛 銀座本店",
    cuisine: "鮨",
    priceTier: "executive",
    priceDinner: "¥30,000〜",
    scenes: ["とっておき", "記念日", "接待", "会食"],
    area: "銀座",
    address: "東京都中央区銀座",
    nearestStation: "銀座駅 徒歩3分",
    lat: 35.6717,
    lng: 139.7649,
    googleMapsUrl: mapsUrl("久兵衛 銀座", 35.6717, 139.7649),
    googlePlaceQuery: "久兵衛 銀座本店",
    image:
      "https://images.unsplash.com/photo-1611143669185-af224c5e3252?w=800&q=80",
    rating: 4.8,
    reviewCount: 420,
    tags: ["老舗", "エグゼクティブ", "記念日"],
    description: "銀座のレジェンド。大切な記念日やハイクラスの接待に。",
    privateRoom: true,
    capacity: 10,
    listSource: "東京レストラン_鮨",
  },
  {
    id: "roppongi-nikkai",
    name: "肉会 六本木",
    cuisine: "肉",
    priceTier: "middle",
    priceDinner: "¥12,000〜",
    scenes: ["会食", "カジュアル", "個室"],
    area: "六本木",
    address: "東京都港区六本木",
    nearestStation: "六本木駅 徒歩4分",
    lat: 35.6627,
    lng: 139.7314,
    googleMapsUrl: mapsUrl("焼肉 六本木", 35.6627, 139.7314),
    googlePlaceQuery: "焼肉 六本木",
    image:
      "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80",
    rating: 4.4,
    reviewCount: 96,
    tags: ["焼肉", "個室", "会食"],
    description: "ZENKIGEN会食リスト向けのミドル焼肉。個室で話しやすい。",
    privateRoom: true,
    capacity: 12,
    listSource: "ZENKIGEN会食リスト_middle / 東京レストラン_肉",
  },
  {
    id: "azabu-wagyu",
    name: "麻布牛庵",
    cuisine: "肉",
    priceTier: "executive",
    priceDinner: "¥25,000〜",
    scenes: ["とっておき", "記念日", "接待", "会食"],
    area: "六本木",
    address: "東京都港区麻布十番",
    nearestStation: "麻布十番駅 徒歩6分",
    lat: 35.6565,
    lng: 139.7352,
    googleMapsUrl: mapsUrl("ステーキ 麻布十番", 35.6565, 139.7352),
    googlePlaceQuery: "ステーキ 麻布十番",
    image:
      "https://images.unsplash.com/photo-1600891964092-4316c288032e?w=800&q=80",
    rating: 4.7,
    reviewCount: 210,
    tags: ["和牛", "個室", "エグゼクティブ"],
    description: "麻布のとっておきステーキ。記念日や重要会食に。",
    privateRoom: true,
    capacity: 6,
    listSource: "東京レストラン_肉",
  },
  {
    id: "nihonbashi-washoku",
    name: "日本橋 懐石 月",
    cuisine: "和食",
    priceTier: "executive",
    priceDinner: "¥22,000〜",
    scenes: ["会食", "個室", "接待", "とっておき"],
    area: "東京",
    address: "東京都中央区日本橋",
    nearestStation: "日本橋駅 徒歩2分",
    lat: 35.6812,
    lng: 139.7745,
    googleMapsUrl: mapsUrl("懐石 日本橋", 35.6812, 139.7745),
    googlePlaceQuery: "懐石 日本橋",
    image:
      "https://images.unsplash.com/photo-1553621042-f6e147245754?w=800&q=80",
    rating: 4.7,
    reviewCount: 155,
    tags: ["懐石", "個室完備", "静かな空間"],
    description: "落ち着いた懐石。クライアント会食の定番候補。",
    privateRoom: true,
    capacity: 8,
    listSource: "東京レストラン_和食",
  },
  {
    id: "shibuya-izakaya",
    name: "渋谷 炉端 ひびき",
    cuisine: "和食",
    priceTier: "casual",
    priceLunch: "¥1,200〜",
    priceDinner: "¥4,000〜",
    scenes: ["カジュアル", "コスパ", "会食"],
    area: "渋谷",
    address: "東京都渋谷区宇田川町",
    nearestStation: "渋谷駅 徒歩5分",
    lat: 35.6612,
    lng: 139.6988,
    googleMapsUrl: mapsUrl("居酒屋 渋谷", 35.6612, 139.6988),
    googlePlaceQuery: "居酒屋 渋谷",
    image:
      "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80",
    rating: 4.2,
    reviewCount: 340,
    tags: ["カジュアル", "コスパ", "気軽"],
    description: "チーム飲みやカジュアル会食に。コスパの良い店リスト入り。",
    privateRoom: false,
    capacity: 20,
    listSource: "コスパの良い店",
  },
  {
    id: "shinjuku-italian",
    name: "Osteria Luce",
    nameEn: "Osteria Luce",
    cuisine: "イタリアン",
    priceTier: "middle",
    priceDinner: "¥10,000〜",
    scenes: ["デート", "記念日", "カジュアル", "会食"],
    area: "新宿",
    address: "東京都新宿区",
    nearestStation: "新宿駅 徒歩8分",
    lat: 35.6895,
    lng: 139.7005,
    googleMapsUrl: mapsUrl("イタリアン 新宿", 35.6895, 139.7005),
    googlePlaceQuery: "イタリアン 新宿",
    image:
      "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80",
    rating: 4.5,
    reviewCount: 188,
    tags: ["パスタ", "ワイン", "デート"],
    description: "新宿の落ち着いたオステリア。ミドル会食にも使える。",
    privateRoom: true,
    capacity: 6,
    listSource: "ZENKIGEN会食リスト_middle",
  },
  {
    id: "minato-french",
    name: "Maison Hibiki",
    nameEn: "Maison Hibiki",
    cuisine: "フレンチ",
    priceTier: "executive",
    priceDinner: "¥28,000〜",
    scenes: ["とっておき", "記念日", "デート", "接待"],
    area: "六本木",
    address: "東京都港区西麻布",
    nearestStation: "乃木坂駅 徒歩7分",
    lat: 35.6588,
    lng: 139.7255,
    googleMapsUrl: mapsUrl("フレンチ 西麻布", 35.6588, 139.7255),
    googlePlaceQuery: "フレンチ 西麻布",
    image:
      "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&h=600&fit=crop&q=80",
    rating: 4.9,
    reviewCount: 92,
    tags: ["フレンチ", "記念日", "ワインペアリング"],
    description: "とっておきの一軒。記念日や特別な会食に。",
    privateRoom: true,
    capacity: 4,
    listSource: "行ってみたい",
  },
  {
    id: "tsukiji-kaisen",
    name: "築地 海鮮丼 朝市",
    cuisine: "和食",
    priceTier: "casual",
    priceLunch: "¥2,000〜",
    priceDinner: "¥3,500〜",
    scenes: ["カジュアル", "コスパ"],
    area: "築地",
    address: "東京都中央区築地",
    nearestStation: "築地駅 徒歩3分",
    lat: 35.6651,
    lng: 139.7725,
    googleMapsUrl: mapsUrl("海鮮丼 築地", 35.6651, 139.7725),
    googlePlaceQuery: "海鮮丼 築地",
    image:
      "https://images.unsplash.com/photo-1580822184713-fc5400e7fe10?w=800&q=80",
    rating: 4.3,
    reviewCount: 512,
    tags: ["海鮮丼", "ランチ", "観光"],
    description: "築地周辺のコスパ海鮮。気軽なランチに最適。",
    privateRoom: false,
    listSource: "築地周辺レストラン / コスパの良い店",
  },
  {
    id: "ginza-tempura",
    name: "銀座 天ぷら 翠",
    cuisine: "和食",
    priceTier: "middle",
    priceLunch: "¥6,000〜",
    priceDinner: "¥14,000〜",
    scenes: ["会食", "個室", "接待"],
    area: "銀座",
    address: "東京都中央区銀座",
    nearestStation: "銀座駅 徒歩5分",
    lat: 35.6721,
    lng: 139.7635,
    googleMapsUrl: mapsUrl("天ぷら 銀座", 35.6721, 139.7635),
    googlePlaceQuery: "天ぷら 銀座",
    image:
      "https://images.unsplash.com/photo-1569058242567-93de6f36f8eb?w=800&q=80",
    rating: 4.6,
    reviewCount: 167,
    tags: ["天ぷら", "カウンター", "会食"],
    description: "銀座の上品な天ぷら。ミドル会食の定番。",
    privateRoom: true,
    capacity: 8,
    listSource: "東京レストラン_和食 / ZENKIGEN会食リスト_middle",
  },
  {
    id: "kyoto-kaiseki",
    name: "京都 祇園 花筏",
    cuisine: "和食",
    priceTier: "executive",
    priceDinner: "¥30,000〜",
    scenes: ["とっておき", "記念日", "接待"],
    area: "京都",
    address: "京都府京都市東山区祇園",
    nearestStation: "祇園四条駅 徒歩8分",
    lat: 35.0037,
    lng: 135.7788,
    googleMapsUrl: mapsUrl("懐石 祇園", 35.0037, 135.7788),
    googlePlaceQuery: "懐石 祇園",
    image:
      "https://images.unsplash.com/photo-1540648635072-3e4e5c5c0b0a?w=800&q=80",
    rating: 4.8,
    reviewCount: 78,
    tags: ["京都", "懐石", "個室"],
    description: "祇園の名店。京都出張の特別な夜に。",
    privateRoom: true,
    capacity: 6,
    listSource: "地方レストラン_名店 / 京都寺院付近",
  },
  {
    id: "kyoto-temple-cafe",
    name: "南禅寺 湯豆腐 瓢亭別邸風",
    cuisine: "和食",
    priceTier: "middle",
    priceLunch: "¥4,500〜",
    priceDinner: "¥9,000〜",
    scenes: ["カジュアル", "デート", "記念日"],
    area: "京都",
    address: "京都府京都市左京区南禅寺",
    nearestStation: "蹴上駅 徒歩10分",
    lat: 35.0116,
    lng: 135.7944,
    googleMapsUrl: mapsUrl("湯豆腐 南禅寺", 35.0116, 135.7944),
    googlePlaceQuery: "湯豆腐 南禅寺",
    image:
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80",
    rating: 4.5,
    reviewCount: 230,
    tags: ["湯豆腐", "庭園", "京都"],
    description: "寺院巡りあとの和やかな一席。",
    privateRoom: true,
    capacity: 10,
    listSource: "京都寺院",
  },
  {
    id: "la-sushi",
    name: "Sushi Nozawa LA",
    cuisine: "鮨",
    priceTier: "executive",
    priceDinner: "$120〜",
    scenes: ["とっておき", "記念日", "デート"],
    area: "ロサンゼルス",
    address: "Los Angeles, CA",
    nearestStation: "West Hollywood",
    lat: 34.0900,
    lng: -118.3617,
    googleMapsUrl: mapsUrl("sushi west hollywood", 34.09, -118.3617),
    googlePlaceQuery: "omakase sushi west hollywood",
    image:
      "https://images.unsplash.com/photo-1553621042-f6e147245754?w=800&h=600&fit=crop&q=80",
    rating: 4.7,
    reviewCount: 640,
    tags: ["LA", "オマカセ", "海外"],
    description: "ロサンゼルス出張時のとっておき鮨。",
    privateRoom: false,
    capacity: 10,
    listSource: "ロサンゼルス",
  },
  {
    id: "la-italian",
    name: "Bestia",
    cuisine: "イタリアン",
    priceTier: "middle",
    priceDinner: "$80〜",
    scenes: ["カジュアル", "デート", "記念日"],
    area: "ロサンゼルス",
    address: "Downtown LA",
    nearestStation: "Arts District",
    lat: 34.0337,
    lng: -118.2294,
    googleMapsUrl: mapsUrl("Bestia Los Angeles", 34.0337, -118.2294),
    googlePlaceQuery: "Bestia Los Angeles",
    image:
      "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&q=80",
    rating: 4.6,
    reviewCount: 2100,
    tags: ["LA", "イタリアン", "人気店"],
    description: "LAの人気イタリアン。友人とのディナーに。",
    privateRoom: false,
    listSource: "ロサンゼルス",
  },
  {
    id: "chuo-yakitori",
    name: "鳥よし 銀座",
    cuisine: "和食",
    priceTier: "middle",
    priceDinner: "¥9,000〜",
    scenes: ["会食", "カジュアル", "接待"],
    area: "銀座",
    address: "東京都中央区銀座",
    nearestStation: "銀座一丁目駅 徒歩4分",
    lat: 35.6745,
    lng: 139.7678,
    googleMapsUrl: mapsUrl("焼鳥 銀座", 35.6745, 139.7678),
    googlePlaceQuery: "焼鳥 銀座",
    image:
      "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800&q=80",
    rating: 4.5,
    reviewCount: 301,
    tags: ["焼鳥", "カウンター", "会食"],
    description: "銀座の上質焼鳥。ミドル会食にぴったり。",
    privateRoom: true,
    capacity: 8,
    listSource: "ZENKIGEN会食リスト_middle",
  },
  {
    id: "want-to-go-omakase",
    name: "鮨 行ってみたい店",
    cuisine: "鮨",
    priceTier: "executive",
    priceDinner: "¥35,000〜",
    scenes: ["とっておき", "記念日"],
    area: "東京",
    address: "東京都港区",
    nearestStation: "白金高輪駅",
    lat: 35.6432,
    lng: 139.7341,
    googleMapsUrl: mapsUrl("鮨 白金", 35.6432, 139.7341),
    googlePlaceQuery: "鮨 白金",
    image:
      "https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56?w=800&q=80",
    rating: 4.9,
    reviewCount: 45,
    tags: ["予約困難", "オマカセ", "行ってみたい"],
    description: "「行ってみたい」リストの本命候補。",
    privateRoom: false,
    capacity: 8,
    listSource: "行ってみたい",
  },
  {
    id: "local-meibutsu",
    name: "金沢 加賀料理 百万石",
    cuisine: "和食",
    priceTier: "middle",
    priceDinner: "¥12,000〜",
    scenes: ["会食", "個室", "記念日"],
    area: "地方",
    address: "石川県金沢市",
    nearestStation: "金沢駅",
    lat: 36.5613,
    lng: 136.6562,
    googleMapsUrl: mapsUrl("加賀料理 金沢", 36.5613, 136.6562),
    googlePlaceQuery: "加賀料理 金沢",
    image:
      "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=800&q=80",
    rating: 4.6,
    reviewCount: 112,
    tags: ["地方名店", "加賀料理", "個室"],
    description: "地方レストラン名店リストから。出張の夜に。",
    privateRoom: true,
    capacity: 10,
    listSource: "地方レストラン_名店",
  },
  {
    id: "akasaka-chinese",
    name: "赤坂 翡翠楼",
    cuisine: "その他",
    priceTier: "middle",
    priceLunch: "¥3,500〜",
    priceDinner: "¥11,000〜",
    scenes: ["会食", "個室", "接待", "カジュアル"],
    area: "東京",
    address: "東京都港区赤坂",
    nearestStation: "赤坂駅 徒歩3分",
    lat: 35.6745,
    lng: 139.7366,
    googleMapsUrl: mapsUrl("中華 赤坂", 35.6745, 139.7366),
    googlePlaceQuery: "中華 赤坂",
    image:
      "https://images.unsplash.com/photo-1525755662778-989d0524087e?w=800&q=80",
    rating: 4.4,
    reviewCount: 201,
    tags: ["中華", "個室", "会食"],
    description: "大人数会食にも対応しやすい個室中華。",
    privateRoom: true,
    capacity: 20,
    listSource: "ZENKIGEN会食リスト_middle",
  },
  {
    id: "ebisu-casual-italian",
    name: "エビス トラットリア",
    cuisine: "イタリアン",
    priceTier: "casual",
    priceDinner: "¥5,000〜",
    scenes: ["カジュアル", "コスパ", "デート"],
    area: "渋谷",
    address: "東京都渋谷区恵比寿",
    nearestStation: "恵比寿駅 徒歩4分",
    lat: 35.6467,
    lng: 139.7101,
    googleMapsUrl: mapsUrl("イタリアン 恵比寿", 35.6467, 139.7101),
    googlePlaceQuery: "イタリアン 恵比寿",
    image:
      "https://images.unsplash.com/photo-1473093296334-435759b4dda7?w=800&q=80",
    rating: 4.3,
    reviewCount: 276,
    tags: ["カジュアル", "ワイン", "コスパ"],
    description: "気軽に寄れる恵比寿のイタリアン。",
    privateRoom: false,
    listSource: "コスパの良い店",
  },
  {
    id: "marunouchi-french",
    name: "丸の内 Bistro Vert",
    cuisine: "フレンチ",
    priceTier: "middle",
    priceLunch: "¥4,800〜",
    priceDinner: "¥13,000〜",
    scenes: ["会食", "接待", "デート"],
    area: "東京",
    address: "東京都千代田区丸の内",
    nearestStation: "東京駅 徒歩5分",
    lat: 35.6812,
    lng: 139.7671,
    googleMapsUrl: mapsUrl("フレンチ 丸の内", 35.6812, 139.7671),
    googlePlaceQuery: "フレンチ 丸の内",
    image:
      "https://images.unsplash.com/photo-1600891964599-f61ba0e24092?w=800&q=80",
    rating: 4.5,
    reviewCount: 143,
    tags: ["丸の内", "ビジネス", "ランチ可"],
    description: "ビジネス街のミドルフレンチ。会食に便利。",
    privateRoom: true,
    capacity: 8,
    listSource: "ZENKIGEN会食リスト_middle",
  },
  {
    id: "tsukiji-unagi",
    name: "築地 うなぎ 山本",
    cuisine: "和食",
    priceTier: "middle",
    priceLunch: "¥5,000〜",
    priceDinner: "¥8,000〜",
    scenes: ["カジュアル", "会食", "コスパ"],
    area: "築地",
    address: "東京都中央区築地",
    nearestStation: "築地市場駅 徒歩6分",
    lat: 35.6648,
    lng: 139.7695,
    googleMapsUrl: mapsUrl("うなぎ 築地", 35.6648, 139.7695),
    googlePlaceQuery: "うなぎ 築地",
    image:
      "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800&q=80",
    rating: 4.4,
    reviewCount: 198,
    tags: ["うなぎ", "築地", "定番"],
    description: "築地周辺のうなぎ名店。",
    privateRoom: false,
    listSource: "築地周辺レストラン",
  },
  {
    id: "yakiniku-value",
    name: "コスパ焼肉 縁",
    cuisine: "肉",
    priceTier: "casual",
    priceDinner: "¥5,500〜",
    scenes: ["カジュアル", "コスパ", "会食"],
    area: "新宿",
    address: "東京都新宿区",
    nearestStation: "新宿三丁目駅 徒歩3分",
    lat: 35.6906,
    lng: 139.7042,
    googleMapsUrl: mapsUrl("焼肉 新宿", 35.6906, 139.7042),
    googlePlaceQuery: "焼肉 新宿 コスパ",
    image:
      "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=800&q=80",
    rating: 4.1,
    reviewCount: 455,
    tags: ["コスパ", "焼肉", "大人数OK"],
    description: "コスパの良い店リストの定番焼肉。",
    privateRoom: true,
    capacity: 16,
    listSource: "コスパの良い店 / 東京レストラン_肉",
  },
  {
    id: "anniversary-sushi",
    name: "鮨 星",
    cuisine: "鮨",
    priceTier: "executive",
    priceDinner: "¥40,000〜",
    scenes: ["記念日", "とっておき", "デート"],
    area: "銀座",
    address: "東京都中央区銀座",
    nearestStation: "銀座駅 徒歩6分",
    lat: 35.6705,
    lng: 139.7655,
    googleMapsUrl: mapsUrl("鮨 銀座 高級", 35.6705, 139.7655),
    googlePlaceQuery: "鮨 銀座",
    image:
      "https://images.unsplash.com/photo-1583623025817-d180a2225852?w=800&q=80",
    rating: 4.9,
    reviewCount: 67,
    tags: ["記念日", "ペアリング", "予約制"],
    description: "記念日専用にリストアップした銀座の鮨。",
    privateRoom: false,
    capacity: 8,
    listSource: "東京レストラン_鮨 / 行ってみたい",
  },
  {
    id: "private-washoku",
    name: "個室和食 静寂",
    cuisine: "和食",
    priceTier: "middle",
    priceDinner: "¥14,000〜",
    scenes: ["個室", "会食", "接待"],
    area: "東京",
    address: "東京都港区虎ノ門",
    nearestStation: "虎ノ門ヒルズ駅 徒歩2分",
    lat: 35.6669,
    lng: 139.7495,
    googleMapsUrl: mapsUrl("個室 和食 虎ノ門", 35.6669, 139.7495),
    googlePlaceQuery: "個室 和食 虎ノ門",
    image:
      "https://images.unsplash.com/photo-1579027989536-b7b1f875659b?w=800&q=80",
    rating: 4.5,
    reviewCount: 89,
    tags: ["完全個室", "ビジネス", "静か"],
    description: "完全個室メインの和食。機密性の高い会食に。",
    privateRoom: true,
    capacity: 12,
    listSource: "東京レストラン_和食 / ZENKIGEN会食リスト_middle",
  },
];

export const cuisines = [
  "和食",
  "鮨",
  "肉",
  "イタリアン",
  "フレンチ",
  "その他",
] as const;

export const priceTiers = [
  { id: "casual" as const, label: "カジュアル", hint: "〜¥8,000" },
  { id: "middle" as const, label: "ミドル", hint: "¥8,000〜¥20,000" },
  { id: "executive" as const, label: "エグゼクティブ", hint: "¥20,000〜" },
];

export const scenes = [
  { id: "会食" as const, label: "会食", description: "ビジネス・お客様との食事" },
  { id: "個室" as const, label: "個室あり", description: "プライベートな空間" },
  { id: "カジュアル" as const, label: "カジュアル", description: "気軽に立ち寄れる" },
  { id: "とっておき" as const, label: "とっておき", description: "特別な一軒" },
  { id: "記念日" as const, label: "記念日", description: "お祝い・アニバーサリー" },
  { id: "コスパ" as const, label: "コスパ良し", description: "満足度の高い価格帯" },
  { id: "接待" as const, label: "接待", description: "フォーマルな接待" },
  { id: "デート" as const, label: "デート", description: "二人の食事に" },
];

export const areas = [
  "東京",
  "築地",
  "六本木",
  "銀座",
  "渋谷",
  "新宿",
  "京都",
  "地方",
  "ロサンゼルス",
] as const;

export const listSources = [
  { id: "zenkigen", label: "ZENKIGEN会食_middle", match: "ZENKIGEN" },
  { id: "washoku", label: "東京_和食", match: "東京レストラン_和食" },
  { id: "sushi", label: "東京_鮨", match: "東京レストラン_鮨" },
  { id: "meat", label: "東京_肉", match: "東京レストラン_肉" },
  { id: "tsukiji", label: "築地周辺", match: "築地" },
  { id: "value", label: "コスパの良い店", match: "コスパ" },
  { id: "local", label: "地方名店", match: "地方" },
  { id: "want", label: "行ってみたい", match: "行ってみたい" },
  { id: "la", label: "ロサンゼルス", match: "ロサンゼルス" },
  { id: "kyoto", label: "京都", match: "京都" },
];

export function getRestaurantById(id: string) {
  return restaurants.find((r) => r.id === id);
}

export function priceLabel(tier: Restaurant["priceTier"]) {
  return priceTiers.find((p) => p.id === tier)?.label ?? tier;
}
